config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users,
             controllers: {
               
                #  sessions: 'sessions',
                #  registrations: 'registrations'
             }
  resources :users

  
  get 'checkout', to: 'checkouts#show'

  root 'home#homepage'
  get 'roulette', to: 'roulette#index'
  get 'roulette/solo', to: 'roulette#solo'
  get 'roulette/coop', to: 'roulette#coop'

  get "/successful_payment", to: "payments#successful_payment" do
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
  end
  
  get "/cancelled_payment", to: "payments#cancelled_payment"

  namespace :api do
    namespace :v1 do
      devise_for :users,
      controllers: {
        
          sessions: 'sessions',
          registrations: 'registrations'
      }
      resources :products
      get 'checkout', to: 'checkouts#show'

      root 'home#homepage'
      get 'roulette', to: 'roulette#index'
      get 'roulette/solo', to: 'roulette#solo'
      get 'roulette/coop', to: 'roulette#coop'
    
      get "/successful_payment", to: "application#successful_payment" do
        session = Stripe::Checkout::Session.retrieve(params[:session_id])
      end
    
      get "/cancelled_payment", to: "application#cancelled_payment"
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist
  validates :email, uniqueness: true

end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]

  def index
    @users = User.all
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:id, :username, :email, :balance)
  end

  def set_user
    @user ||= User.find(params[:id])
    @products = Product.order(created_at: :ASC)  
  end
  
end 

app/views/users/index.html.erb
	<h1>All Users</h1>
  <table class="table table-hover" table-layout: fixed>
	  <thead>
	    <tr>
	      <th scope="col">ID#</th>
	      <th scope="col">Username</th>
	      <th scope="col">User e-mail</th>
	      <th scope="col">User balance</th>
	    </tr>
	  </thead>
	  <tbody>
	<% @users.sort.each_with_index do |user, index| %>
	    <tr>
	      <th class="align-middle" scope="row"><%= user.id %></th>
	      <td class="align-middle"><%= link_to user.username, user %></td>
	      <td class="align-middle"><%= link_to user.email, user %></td>
	      <td class="align-middle"><%= user.balance %></td>
	    </tr>
	<% end %>
	  </tbody>
	</table>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h2><%= @user.email%> <p></h2>
</p>
<h3>Balance <%= @user.balance %> $</h3>
</p>

  <% @products.each do |product| %>
    <td><%= button_to "Add #{product}$", checkout_path, params: { id: product.id }, method: :get, remote: true, class: local_assigns[:class],
    style: (local_assigns[:class] || local_assigns[:style]) ? local_assigns[:style] : 'background-color:#6772E5;color:#FFF;padding:8px 12px;border:0;border-radius:4px;font-size:1em' %></td><br>
  <% end %>