config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users,
             controllers: {
               
                #  sessions: 'sessions',
                #  registrations: 'registrations'
             }
  resources :users

  
  get 'checkout', to: 'checkouts#show'

  root 'home#homepage'
  get 'roulette', to: 'roulette#index'
  get 'roulette/solo', to: 'roulette#solo'
  get 'roulette/coop', to: 'roulette#coop'

  get "/successful_payment", to: "payments#successful_payment" do
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
  end
  
  get "/cancelled_payment", to: "payments#cancelled_payment"

  namespace :api do
    namespace :v1 do
      devise_for :users,
      controllers: {
        
          sessions: 'sessions',
          registrations: 'registrations'
      }
      resources :products
      get 'checkout', to: 'checkouts#show'

      root 'home#homepage'
      get 'roulette', to: 'roulette#index'
      get 'roulette/solo', to: 'roulette#solo'
      get 'roulette/coop', to: 'roulette#coop'
    
      get "/successful_payment", to: "application#successful_payment" do
        session = Stripe::Checkout::Session.retrieve(params[:session_id])
      end
    
      get "/cancelled_payment", to: "application#cancelled_payment"
    end
  end
  
end

app/views/layouts/_header.html.erb
    <header class="p-3 bg-dark text-white">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <svg class="bi me-2" width="30" height="5"></svg>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <%= link_to "Roula", root_path, class:"navbar-brand mb-0 h1" %>
          <%# <%= link_to "Products", products_path, class:"navbar-brand mb-0 h1" %> 
          <%= link_to "Users", users_path, class:"navbar-brand mb-0 h1" %>
        </ul>
        <% if user_signed_in? %>
        <div class="dropdown text-end">
          <a class="d-block link-white text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %></a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" <%= link_to 'My Page', current_user%></a></li>
              <li><a class="dropdown-item" <%= link_to 'Profile Settings', edit_user_registration_path, method: :get%></a></li>
              <li><hr class="dropdown-divider"></li>
              <a class="dropdown-item link-danger" <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" } %></a></li>
            </ul>
        </div>           
        <% else %>
        <div class="col-md text-end"></div>
          <a href="/users/sign_in" class="btn btn-outline-primary me-2 " role="button" aria-pressed="true">Login</a>&ensp;
          <a href="/users/sign_up" class="btn btn-primary" role="button" aria-pressed="true">Sign-up</a>
        <% end %>
    </header>

        <% if notice %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <center><%= notice %></center>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% elsif alert %>
          <div class="alert alert-danger "><center><%= alert %></center></div>
        <% else %>
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
              <center><%= message %></center>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          <% end %>
        <% end %>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoulaApi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p>
      <div class="container" align="center"> 
      <%= yield %>
    </div>
  </body>
</html>